from fastapi import FastAPI, File, UploadFile, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import tensorflow as tf
from PIL import Image
import io
import numpy as np
import logging
import uuid

from src.config import (
    APP_TITLE,
    APP_DESCRIPTION,
    APP_VERSION,
    CLASS_NAMES,
    IMG_HEIGHT,
    IMG_WIDTH,
    ALLOWED_ORIGINS,
    ALLOWED_METHODS,
    ALLOWED_HEADERS,
    ALLOWED_CREDENTIALS,
)
from src.model_loader import load_inference_model, get_loaded_model

from src.mongodb_service import (
    initialize_mongodb,
    get_mongo_db,
    insert_record,
    get_records_by_device_id,
)

logger = logging.getLogger(__name__)

# --- FastAPI Application Instance ---
app = FastAPI(
    title=APP_TITLE,
    description=APP_DESCRIPTION,
    version=APP_VERSION,
)

# --- CORS Middleware ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=ALLOWED_CREDENTIALS,
    allow_methods=ALLOWED_METHODS,
    allow_headers=ALLOWED_HEADERS,
)


# --- FastAPI Startup Event: Initialize ML Model and MongoDB ---
@app.on_event("startup")
async def startup_event():
    """
    Initializes the ML model and MongoDB client when the FastAPI application starts.
    """
    logger.info("Application startup event triggered.")

    # Initialize MongoDB first
    try:
        initialize_mongodb()
        logger.info("MongoDB initialization complete.")
    except Exception as e:
        logger.critical(f"Failed to initialize MongoDB during startup: {e}")
        # Depending on criticality, you might sys.exit(1) here for hard failure

    # Then load the ML model
    try:
        load_inference_model()
        logger.info("ML model loading complete.")
    except Exception as e:
        logger.critical(f"Failed to load ML model during startup: {e}")
        # Depending on criticality, you might sys.exit(1) here for hard failure

    logger.info("Application startup process completed.")


# --- Health Check Endpoint ---
@app.get("/health", summary="Health Check", response_model=dict)
async def health_check():
    """
    Checks the health of the API, ensures the ML model is loaded and responsive,
    and verifies MongoDB connectivity.
    """
    # Check ML Model
    ml_model_ok = False
    try:
        model_layer = get_loaded_model()
        if model_layer is not None:
            dummy_input = tf.constant(
                np.zeros((1, IMG_HEIGHT, IMG_WIDTH, 3), dtype=np.float32)
            )
            _ = model_layer(dummy_input)
            ml_model_ok = True
            logger.info("Health check: ML model responsive.")
        else:
            logger.warning("Health check: ML model is not loaded.")
    except Exception as e:
        logger.error(f"Health check failed due to ML model inference error: {e}")
        ml_model_ok = False

    # Check MongoDB
    mongodb_ok = False
    try:
        db_client = get_mongo_db()
        if db_client is not None:
            # Attempt a minimal MongoDB operation (e.g., ping the server)
            db_client.admin.command("ping")  # Blocks, but is a robust check
            mongodb_ok = True
            logger.info("Health check: MongoDB connected.")
        else:
            logger.warning("Health check: MongoDB client not initialized.")
    except Exception as e:
        logger.error(f"Health check failed due to MongoDB error: {e}")
        mongodb_ok = False

    status = "ok" if ml_model_ok and mongodb_ok else "error"
    return {"status": status, "model_loaded": ml_model_ok, "mongodb_ok": mongodb_ok}


# --- Prediction Endpoint ---
@app.post("/predict", summary="Predict Sheep Pain", response_model=dict)
async def predict_pain(
    file: UploadFile = File(...),
    x_device_id: str = Header(
        None,
        alias="X-Device-ID",
        description="Unique device identifier from the client. Generated if not provided.",
    ),
):
    """
    Accepts an image file of a sheep, preprocesses it, predicts
    whether the sheep is in pain, and stores the record in MongoDB
    associated with the provided device ID.

    - **file**: Upload a sheep image in JPG or PNG format.
    - **X-Device-ID**: Optional. A unique identifier generated by the client device.
                       If not provided, a UUID will be generated for the record.
    """
    if not x_device_id:
        x_device_id = str(uuid.uuid4())  # Generate a UUID if client doesn't provide one
        logger.info(f"No X-Device-ID provided. Generating new ID: {x_device_id}")

    if not file.content_type.startswith("image/"):
        logger.warning(f"Invalid file type uploaded: {file.content_type}")
        raise HTTPException(
            status_code=400,
            detail="Invalid file type. Please upload an image (JPG, PNG).",
        )

    record_id = None
    try:
        # Get the loaded model (it should already be loaded at startup)
        model_layer = get_loaded_model()
        if model_layer is None:
            logger.error("ML model not available for prediction.")
            raise HTTPException(
                status_code=500,
                detail="ML model is not loaded. Please check backend logs.",
            )

        # 1. Read image content
        contents = await file.read()
        image = Image.open(io.BytesIO(contents)).convert("RGB")

        # 2. Preprocess image for model input
        image = image.resize((IMG_WIDTH, IMG_HEIGHT))
        image_array = np.array(image) / 255.0
        input_tensor = tf.constant(
            np.expand_dims(image_array, axis=0), dtype=tf.float32
        )

        # 3. Perform inference
        logger.info(
            f"Performing inference for file: {file.filename} for device: {x_device_id}"
        )
        predictions = model_layer(input_tensor)
        pain_probability = float(predictions["output_0"].numpy()[0][0])

        # 4. Interpret predictions
        prediction_label = CLASS_NAMES[1] if pain_probability >= 0.5 else CLASS_NAMES[0]
        confidence = max(pain_probability, 1 - pain_probability)

        logger.info(
            f"Prediction for {file.filename} (device: {x_device_id}): '{prediction_label}' (Prob: {pain_probability:.4f}, Conf: {confidence:.4f})"
        )

        # 5. Store record in  MongoDB
        try:
            record_data = {
                "filename": file.filename,
                "prediction": prediction_label,
                "pain_probability": pain_probability,
                "confidence": confidence,
                # 'device_id' added by insert_record function
            }
            record_id = await insert_record(x_device_id, record_data)
            logger.info(
                f"Record stored in MongoDB with ID: {record_id} for device: {x_device_id}"
            )
        except Exception as db_e:
            logger.error(
                f"Failed to store record in MongoDB for device {x_device_id}: {db_e}"
            )
            # Do not re-raise, allow prediction to be returned even if DB fails.

        # 6. Return structured JSON response
        response_content = {
            "filename": file.filename,
            "prediction": prediction_label,
            "pain_probability": pain_probability,
            "confidence": confidence,
        }
        if record_id:
            response_content["record_id"] = record_id

        return JSONResponse(content=response_content)

    except HTTPException:
        raise  # Re-raise HTTPExceptions (e.g., 400 Invalid file type)
    except Exception as e:
        logger.exception(
            f"Error processing prediction for {file.filename} (device: {x_device_id}): {e}"
        )
        raise HTTPException(
            status_code=500,
            detail=f"An internal server error occurred during prediction: {e}",
        )


# --- Endpoint: Get All Records for a Device ---
@app.get(
    "/records", summary="Get All Sheep Pain Records for a Device", response_model=dict
)
async def get_all_records(
    x_device_id: str = Header(
        ...,
        alias="X-Device-ID",
        description="Unique device identifier from the client.",
    )
):
    """
    Retrieves all stored sheep pain prediction records associated with the provided device ID.
    """
    if not x_device_id:
        logger.warning("X-Device-ID header is missing for /records endpoint.")
        raise HTTPException(status_code=400, detail="X-Device-ID header is required.")

    records_list = []
    try:
        records_list = await get_records_by_device_id(x_device_id)
        logger.info(
            f"Retrieved {len(records_list)} records for device ID: {x_device_id}"
        )
        return JSONResponse(content={"records": records_list})

    except ConnectionError:
        raise HTTPException(
            status_code=500,
            detail="Database not initialized. Please check backend startup logs.",
        )
    except Exception as e:
        logger.exception(
            f"Error retrieving records from MongoDB for device {x_device_id}: {e}"
        )
        raise HTTPException(
            status_code=500,
            detail=f"An internal server error occurred while retrieving records: {e}",
        )
